
spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password= # Se tiver senha, adicione aqui
spring.redis.jedis.pool.max-active=10
spring.redis.jedis.pool.max-idle=5
spring.redis.jedis.pool.min-idle=1
